.\"
.\" Copyright (c) 2020, 2021 Matthias Pressfreund
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: May 14 2021 $
.Dt PFTBLD.CONF 5
.Os
.Sh NAME
.Nm pftbld.conf
.Nd configuration file for the
.Xr pf 4
table content management daemon
.Sh DESCRIPTION
.Nm
is the configuration file for
.Xr pftbld 8 .
.Sh TYPES
In this context, the following rules regarding parameter value types apply:
.Pp
.Bl -bullet -offset indent -compact
.It
Values of type
.Ar time
must be given as a sequence of number/unit combinations, with numbers in
decimal format, e.g.
.Pa 7w3d
representing a period of 7 weeks and 3 days.
Valid units are:
.Bd -literal -offset indent
w (weeks)
d (days)
h (hours)
m (minutes)
s (seconds)
.Ed
.Pp
.It
Values of type
.Ar number
are usually specified in decimal format.
If a leading zero is given, octal format is assumed
.Pq e.g. Pa 0740 ,
which is typically used with the
.Ic socket mode
option.
.Pp
.It
Values of type
.Ar path
must be provided as absolute paths unless a base path is provided via the
.Fl b
option on daemon startup.
.Pp
.It
Values of type
.Ar address/network ,
when from the IPv4 family, may be specified in short CIDR form with one to four
octets and an optional prefix length suffix.
Omitted octets are assumed zero.
In general, all numbers of an IPv4 address must be specified in decimal form
while IPv6 addresses must consist of hexadecimal numbers except of the lower
four octets which may as well be presented in decimal IPv4 style, as in
.Pp
.Dl ::FFFF:192.168.100.1
.Pp
If no prefix length is specified, all 128 bits are assumed for IPv6.
With IPv4, the total length of octets from the most significant to that with
the least significant set bit is used.
.Pp
Below a few examples to illustrate the above:
.Bd -literal -offset indent
           11.22.33.44/32 <--> 11.22.33.44
           11.22.33.0/24  <--> 11.22.33.0 - 11.22.33.255
11.22 <--> 11.22.0.0/16   <--> 11.22.0.0 - 11.22.255.255
11    <--> 11.0.0.0/8     <--> 11.0.0.0 - 11.255.255.255
11/17 <--> 11.0.0/17      <--> 11.0.0.0 - 11.0.127.255
.Ed
.El
.Sh GLOBAL CONFIGURATION
Here are the settings that may be applied globally:
.Bl -tag -width Ds
.It Oo Ic no Oc Ic backlog Ar number
The maximum allowed number of simultaneous connections on a
.Ic socket .
In case the
.Ic no
keyword is used instead of a
.Ar number ,
only one connection will be allowed at a time.
If not specified, the default value of 5 connections will be used.
The actual upper limit of this parameter is the value of the
.Pa kern.somaxconn
kernel state which can be determined by means of the
.Xr sysctl 8
utility.
.It Oo Ic no Oc Ic datamax Ar bytes
This limits the number of
.Ar bytes
allowed to be transmitted per connection, the terminating
.Sq Dv \e0
character included.
In case a client exceeds this limit, the connection will be closed and all
transmitted data will be discarded.
If the
.Ic no
keyword is specified instead of the number of
.Ar bytes ,
no limit is applied to the amount of data accepted by a connection.
Defaults to 2048 bytes per connection.
.It Oo Ic no Oc Ic drop Ar time
The amount of time (from the moment it is received) after which a managed IP
address will be discarded/dropped from
.Xr pftbld 8
memory.
In case the
.Ic no
keyword is used instead of a
.Ar time
value, IP addresses will be kept forever.
.It Ic exclude Ar option | Brq ...
Specifies exclusion criteria for incoming data.
Multiple criterias may be either specified one at a time or enclosed in curly
braces.
Valid options are:
.Bl -tag -width Ds
.It Ic keyterm Ar string
Skip processing of incoming data containing the given
.Ar string .
.It Ic keytermfile Ar path
Read
.Ic keyterm
strings line by line from the file at
.Ar path .
.It Ic localhosts
Exclude all IP addresses found in the local host name lookup file
.Pa /etc/hosts
from being processed.
.It Ic net Ar address/network
Exclude the specified
.Ar address/network
(e.g.
.Ar 192.168.100/24 )
from being processed.
.It Ic netfile Ar path
Read
.Ic net
entries line by line from the file at
.Ar path .
The file must be fomatted as outlined in
.Xr hosts 5 .
Lines not starting with a valid
.Pa address/network
are logged and ignored.
.El
.It Oo Ic no Oc Ic idlemin Ar milliseconds
Specifies the minimum time that must elapse between successive occurrences of
an IP address on a
.Pa data socket
in order to be recognized and counted as separate.
Faster recurrences are considered duplicates and are ignored.
This prevents appearance counters from being increased before the system is
able to process and respond to incoming data.
Although the maximum number of
.Ar milliseconds
is 32767, values greater than 1000 are rather uncommon.
Duplicate detection may be disabled by specifying the
.Ic no
keyword instead of the number of
.Ar milliseconds .
Defaults to 250 milliseconds.
.It Ic include Ar option | Brq ...
Specifies inclusion criteria for incoming data overriding exclusion criteria
specified by
.Ic exclude .
Please note that in case client data has a match in some
.Ic include keyterm ,
it still might be excluded by a matching
.Ic exclude net
criteria.
Multiple criterias may be either specified one at a time or enclosed in curly
braces.
Valid options are:
.Bl -tag -width Ds
.It Ic keyterm Ar string
Make sure processing of incoming data containing the given
.Ar string
takes place even if a matching
.Ic exclude keyterm
criteria is defined.
.It Ic keytermfile Ar path
Read
.Ic keyterm
strings line by line from the file at
.Ar path .
.It Ic net Ar address/network
Make sure the specified
.Ar address/network
(e.g.
.Ar 192.168.100/24 )
will be processed even if a matching
.Ic exclude net
criteria is defined.
.It Ic netfile Ar path
Read
.Ic net
entries line by line from the file at
.Ar path .
The file must be fomatted as outlined in
.Xr hosts 5 .
Lines not starting with a valid
.Pa address/network
are logged and ignored.
.El
.It Oo Ic no Oc Ic log Ar path
Make
.Xr pftbld 8
write its log to the file at
.Pa path
instead of the default log file
.Pa /var/log/pftbld.log .
Logging may be completely disabled by using the leading
.Ic no
keyword instead of specifying a
.Ar path .
.It Oo Ic no Oc Ic timeout Ar milliseconds
Sets the maximum time for a client to transmit its data after making a
connection.
If a client does not succeed sending data within the specified number of
.Ar milliseconds ,
the connection will be closed and all transmitted data will be discarded.
In order to disable this timeout, the
.Ic no
keyword may be specified instead of the number of
.Ar milliseconds .
The default value is 10000 milliseconds.
.El
.Sh TARGETS
Typically, targets are used to distinguish input data by service type and apply
appropriate handling.
An IP address transmitted by a client is always (automatically) assigned to a
.Ic target .
Since the same IP address may be submitted by different clients via their own
sockets which may be assigned to different targets, this combination (also
known as
.Pa client entry )
is by nature a many-to-many relationship, i.e. one IP address may be assigned
to multiple targets as well as multiple addresses may be associated with the
same target.
.Pp
In order to start
.Xr pftbld 8 ,
at least one
.Ic target
needs to be defined.
.Bl -tag -width Ds
.It Ic target Ar name Brq ...
The
.Pa name
must be an explicit identifier, ideally reflecting the corresponding service
name, followed by a block of options enclosed in curly braces:
.Bl -tag -width Ds
.It Ic cascade Brq ...
Specifies frame and first
.Ic step
of a
.Xr pf 4
.Ic table
cascade associated client entries will traverse during their
.Xr pftbld 8
life cycle.
There must be exactly one instance defined per
.Ic target ,
followed by a block of options enclosed in curly braces:
.Bl -tag -width Ds
.It Oo Ic no Oc Ic drop Ar time
Overrides any
.Ic drop
option specified globally or with the enclosing
.Ic target .
.It Ic expire Ar time
Specifies the period of time an IP address will be held in the corresponding
.Ic table .
If omitted,
addresses do not expire and remain in their tables until deleted manually, e.g.
by using the
.Xr pftblctl 8
.Ic drop
command.
.It Ic hits Ar number
Maximum number of appearances for a specific IP address in the corresponding
.Ic table .
If
.Ar number
is exceeded by an IP address, it will move on to the next
.Ic step .
In order to properly close a
.Ic cascade ,
this option needs to be omitted on the last
.Ic step
as this makes
.Xr pftbld 8
stop evaluating the appearance count of an IP address.
.It Ic kill | keep Ar option | Brq ...
Set/Unset kill options used when adding an address to a
.Ic table .
Multiple options may be either specified one at a time or enclosed in curly
braces.
Valid options are:
.Bl -tag -width Ds
.It Ic nodes
Refers to a reported address'
.Pa source nodes .
The default is
.Ic keep .
.It Ic states
Refers to a reported address'
.Pa state entries .
The default is
.Ic kill .
.El
.Pp
Generally, kill options are applied to the current
.Ic step
and all its successors, until revoked by their counterparts.
.It Ic step Ar option | Brq ...
The next step in the cascade followed by at least one
.Ic cascade
.Ar option
(except
.Ic step
itself), multiple options enclosed in curly braces.
If there is no
.Ic table
.Ar option
specified for a
.Ic step ,
it is inherited from its predecessor.
Steps are traversed in the order of their appearance.
.It Ic table Ar name
The
.Ar name
of the corresponding
.Xr pf 4
table.
This option is mandatory at
.Ic cascade
definition and optional for every enclosed
.Ic step .
.sp
It should also be noted that while sharing tables is discouraged, unmanaged
entries added by other means coexist perfectly and neither interfere with nor
get affected by those created and managed by
.Xr pftbld 8 .
.El
.It Oo Ic no Oc Ic drop Ar time
Overrides the global
.Ic drop
option.
.It Ic exclude Ar option | Brq ...
Allows for
.Ic target
specific exclusion criteria additional (and evaluated prior) to global
.Ic exclude
settings.
.It Oo Ic no Oc Ic idlemin Ar milliseconds
Overrides the global
.Ic idlemin
option.
.It Ic include Ar option | Brq ...
Allows for
.Ic target
specific inclusion criteria additional (and evaluated prior) to global
.Ic include
settings.
.It Ic persist Ar path
Specifies a file at
.Ar path
in which managed IP addresses are saved when the daemon shuts down and from
which they are loaded on startup.
Each line of the file contains three space-separated fields:
.Pp
.Bl -enum -offset indent -compact
.It
The IP address.
.It
The number of appearances.
.It
The UNIX timestamp of the last appearance.
.El
.Pp
This option may also be used to initialize the daemon's memory on startup by
submitting a list of plain IP addresses (one per line) without any further
information.
In this case, the other two fields are initialized as follows:
.Pp
.Bl -bullet -offset indent -compact
.It
The number of appearances is set to 1.
.It
The time stamp of the last appearance is set to the current time.
.El
.It Ic skip Ar number
Makes
.Xr pftbld 8
add the IP address of a new client entry to the corresponding
.Xr pf 4
table only after the specified
.Ar number
of appearances.
.It Ic socket Ar path Oo Bro ... Brc Oc
Specifies a UNIX-domain socket at
.Ar path
to be used for sending target specific
.Pa data strings
to
.Xr pftbld 8 .
At least one data socket must be specified per
.Ic target ,
followed by an optional block of parameters enclosed in curly braces:
.Bl -tag -width Ds
.It Ic action add | delete | drop
Specifies how to process IP addresses received through the parent
.Ic socket .
The default action is
.Ic add ,
creating a new client entry and inserting the address into the corresponding
.Xr pf 4
table.
The
.Ic delete
action removes the address from the corresponding table as if it just had
expired.
If
.Ic drop
is specified, the address will not just be deleted, but the associated client
entry will also be completely removed from the daemon's memory.
.It Oo Ic no Oc Ic backlog Ar number
Overrides the global
.Ic backlog
value.
.It Oo Ic no Oc Ic datamax Ar bytes
Overrides the global
.Ic datamax
value.
.It Ic group Ar id | name
The group of the
.Ic socket ,
either as a numeric group
.Ar id
or as a
.Ar name
to derive the
.Ar id
from.
Defaults to the group of the parent directory.
.It Ic id Ar name
Appends
.Ar name
to the
.Ar name
of the enclosing
.Ic target
in all log entries and in the process list.
This is mandatory in case there is more than one
.Ic socket
defined for a target as it later allows for their identification.
The combination of
.Ic target
.Ar name
and
.Ic id
.Ar name
must be unique.
.It Ic mode Ar number
The absolute mode of the
.Ic socket ,
preferably as an octal
.Ar number .
Defaults to 0660.
.It Ic owner Ar id | name
The owner of the
.Ic socket ,
either as a numeric user
.Ar id
or as a
.Ar name
to derive the
.Ar id
from.
Defaults to the owner of the parent directory.
.It Oo Ic no Oc Ic timeout Ar milliseconds
Overrides the global
.Ic timeout
value.
.El
.El
.El
.Sh FILES
.Bl -tag -width "/etc/pftbld/pftbld.conf" -compact
.It Pa /etc/hosts
Local host name lookup file.
.It Pa /etc/pftbld/pftbld.conf
Default configuration file path.
.It Pa /var/run/pftbld.sock
Default control socket.
.El
.Sh EXAMPLES
The following
.Nm
example specifies a
.Pa www
target with a
.Pa data socket
inside the default
.Xr chroot 8
directory of the
.Xr httpd 8
server, allowing for instant reporting of offending clients.
.Bd -literal -offset indent
exclude {
	localhosts
	net "10.0.0/24"
}

drop 3w

target "www" {
	persist "/etc/pftbld/clientaddr.list"
	exclude keytermfile "/etc/pftbld/keyterms.list"

	socket "/var/www/run/pftbld-www.sock" {
		owner "www"
		group "www"
	}

	cascade {
		table "attackers"
		hits 4
		expire 1h

		step {
			hits 12
			expire 6h
		}
		step {
			expire 5d
			no drop
			kill nodes
		}
	}
}
.Ed
.Pp
The first 4 times an address (outside the
.Pa 10.0.0/24
network and the hosts found in
.Pa /etc/hosts )
is reported, it will be added to the
.Pa attackers
table for 1 hour.
From the 5th until the 12th time, the address will remains in the same table
for 6 hours.
Until here, if an address is not reported for 3 weeks, it will be dropped from
memory.
Related state entries will be killed while source nodes will be kept (the
default).
.Pp
From the 13th appearance forth, an address will be held in the
.Pa attackers
table for 5 days, is not going to be dropped from memory anymore and source
nodes will be killed along with state entries.
.Pp
The
.Xr pftbld 8
binary in pipe mode may be used for testing:
.Bd -literal -offset indent
# echo -n "11.22.33.44" | pftbld -p /var/www/run/pftbld-www.sock
.Ed
.Pp
Alternatively, the same result can be achieved by utilizing
.Xr pftblctl 8
along with
.Fl q
suppressing the server acknowledge that would be printed to
.Pa stdout
otherwise:
.Bd -literal -offset indent
# pftblctl -q -s /var/www/run/pftbld-www.sock 11.22.33.44
.Ed
.Pp
If everything went right, two entries were appended to the default log file
.Pa /var/log/pftbld.log .
The first telling that the address
.Pa 11.22.33.44
has hit the
.Pa www
target and the second that the address has been added to the
.Pa attackers
.Xr pf 4
table and will be kept there for the next hour.
.Pp
Removing the address from
.Xr pftbld 8
memory (and the
.Pa attackers
table) can be achieved by sending a
.Pa drop
command to the
.Pa control socket :
.Bd -literal -offset indent
# pftblctl drop 11.22.33.44
1 client entry dropped.
.Ed
.Pp
In order to keep offending clients away from
.Xr httpd 8 ,
appropriate entries in
.Xr pf.conf 5
are required.
Here's an example:
.Bd -literal -offset indent
table <attackers> persist
block in quick log proto tcp from <attackers> to port { www https }
.Ed
.Pp
On a FastCGI supported web server, the following PHP code snippet allows for
automatic notifications:
.Bd -literal -offset indent
function pftbld_feed() {
	$sock = socket_create(AF_UNIX, SOCK_STREAM, 0);
	if ($sock === false)
		return;
	if (socket_connect($sock, '/run/pftbld-www.sock') !== false)
		socket_write($sock,
		    "{$_SERVER['REMOTE_ADDR']}\\n".
		    "{$_SERVER['REQUEST_URI']}\\n".
		    "{$_SERVER['HTTP_USER_AGENT']}");
	socket_close($sock);
}
.Ed
.Pp
In case a web application should be capable to, for instance, drop client
entries from
.Xr pftbld 8
autonomously, at first an additional
.Ic socket
entry, this time with the
.Ic action drop
option is required in the configuration:
.Bd -literal -offset indent
target "www" {
	...
	socket "/var/www/run/pftbld-www-drop.sock" {
		action drop
		owner "www"
		group "www"
	}
	...
}
.Ed
.Pp
Now, the above PHP code may simply be reused as follows:
.Bd -literal -offset indent
function pftbld_drop() {
	$sock = socket_create(AF_UNIX, SOCK_STREAM, 0);
	if ($sock === false)
		return;
	if (socket_connect($sock,
	    '/run/pftbld-www-drop.sock') !== false)
		socket_write($sock,
		    "{$_SERVER['REMOTE_ADDR']}\\n".
		    "client ok");
	socket_close($sock);
}
.Ed
.Sh SEE ALSO
.Xr pf 4 ,
.Xr pf.conf 5 ,
.Xr pftblctl 8 ,
.Xr pftbld 8
.Sh AUTHORS
.An -nosplit
The
.Xr pftbld 8
program was written by
.An Matthias Pressfreund .
